---
   - name: Installing Composer
     shell: sudo composer install --no-dev --prefer-source --no-interaction
     args:
       chdir: /var/www/snipeit/

   - name: Permission 1
     shell: sudo chown -R www-data:www-data /var/www/snipeit/

   - name: Permission 2
     shell: sudo chmod -R 755 /var/www/snipeit/
